[workspace]
authors = ["knmcguire <kimberleymcguire@gmail.com>"]
channels = ["conda-forge", "https://prefix.dev/robostack-lyrical"]
name = "ros2_canary"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[target.linux-64.activation]
scripts = ["install/setup.bash"]

[target.win.activation]
scripts = ["install/setup.bat"]

[tasks]
build = "colcon build --catkin-skip-building-tests"
test = "colcon test --event-handlers console_direct+"
test-result = "colcon test-result --all"

[dependencies]
ros-lyrical-desktop = ">=0.13.0,<0.14"
ros-dev-tools = ">=1.0.2,<2"
