<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>canary</name>
  <version>0.0.1</version>
  <description>Metapackage for the canary project, a collection of simple ROS 2 example/demo packages.</description>
  <maintainer email="maintainer@example.com">canary maintainers</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>canary_cpp</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
